# [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)

## Key Dependancies:

1. IPython and Jupyter
2. NumPy: efficient storage and manipulation of dense data arrays
3. Pandas: provides the DataFrame for efficient storage and manipulation of labeled/columnar data
4. Matplotlib: flexible range of data visualizations
5. Scikit-Learn: efficient and clean implementations of important and estabablished machine learning algorithms

## Installation
Install miniconda or anaconda then the packages for this:
`conda install numpy pandas scikit-learn matplotlib seaborn jupyter`

## Documentation
?: shows documentation  
??: shows sourcecode

## NumPy

In [2]:
# check the version of numpy
import numpy
numpy.__version__

'1.12.1'

In [3]:
# import as an alias
import numpy as np

In [5]:
# check namespace via autocomplete
# np.<TAB>

In [6]:
# check documentation
np?

### Data Types in python
- Data types are dynamically typed.
- This means we can assign any kind of data to any variable

In [8]:
# switch x from an integer to a string
x = 4
print(x)

x = "four"
print(x)

4
four


integers:
- actually a pointer

Lists

In [10]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
type(L[0])

int

In [12]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(L2[0])

str

In [14]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

Fixed type arrays

In [16]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Here, 'i' means that the contents are integers. ndarray from numpy allows for efficent operations on the data

### Creating arrays from python lists

In [17]:
# integer arrays:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [18]:
# upcasted to a uniform data type
np.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [19]:
# explicitly set the data type with dtype
np.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [25]:
# multi-dimensional arrays
# nested lists result in these
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating arrays from scratch
- we may want to create a large array

In [26]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
# create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [28]:
# create a 3x5 array filled with 3.14
np.full([3, 5], 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [29]:
# create a linear sequence array
# starting with 0, ending at 20, and stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# create an array of 5 values, evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [31]:
# create a 3x3 array of uniformly distribued 
# random values between 0 and 1
np.random.random([3, 3])

array([[ 0.40313467,  0.98115062,  0.47114332],
       [ 0.18809273,  0.54643531,  0.93810403],
       [ 0.03606709,  0.47803966,  0.64296618]])

In [32]:
# create an array of 3x3 normally distributed random values
# with a mean of 0 and standard deviation of 1
np.random.normal(0, 1, (3, 3))

array([[-0.59195007,  1.32116139,  0.45499338],
       [-0.86947637, -1.67532737, -0.77642893],
       [ 0.9945531 , -0.21690609,  0.71891321]])

In [33]:
# create a 3x3 array of random integers in the interval [0, 10]
np.random.randint(0, 10, (3, 3))

array([[5, 6, 6],
       [9, 0, 7],
       [5, 4, 9]])

In [34]:
# create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [35]:
# create an uninitialized array of 3 integers
# values are what happens to be in that memory location
np.empty(3)

array([ 1.,  1.,  1.])

### NumPy Standard Data types
to specify the data type, user a string or the np object

### Basics of Numpy Arrays
- Lets look at how to:
    - access data and subarrays
    - split
    - reshape
    - join
    

#### Array attributes

In [13]:
import numpy as np
np.random.seed(0) # for reproducibility

x1 = np.random.randint(10, size=6) # 1d array
x2 = np.random.randint(10, size=(3, 4)) # 2d array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3d array

In [43]:
# each has ndim (number of dimensions), shape (size of each dimension), dtype (type of array), and size (total size)
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int64


In [42]:
# we can also get the itemsize (size in btyes of each item) and nbytes (total size in bytes of the array)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


#### Array Indexing: Accessing single elements

In [14]:
x1[0]

5

In [15]:
x1[4]

7

In [16]:
# index from the end of the array, use negative numbers
x1[-1]

9

In [17]:
x1[-2] 

7

In [18]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [19]:
# multi-dimensional arrays can be accessed using a comma-separated tuple of indices
x2[0,0]

3

In [20]:
x2[2, 0]

1

In [21]:
x2[2, -1]

7

In [23]:
# values can be modified using the above notation
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [24]:
# because numpy arrays have a fixed data-type, values get truncated
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

#### Array slicing: Accessing subarrays
using the notation 
```
x[start:stop:step]
```
allows for accessing individual array elements

##### 1d arrays

In [26]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# the first 5 elements
x[:5]

array([0, 1, 2, 3, 4])

In [28]:
# elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [29]:
# middle sub array
x[4:7]

array([4, 5, 6])

In [30]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [31]:
# every other element starting with index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [32]:
# a negative step swaps the start and stop.
# convenient for reversing an array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
# reversed array starting with index 5, and every other element
x[5::-2]

array([5, 3, 1])

##### Multi-dimensional subarrays
Works the same way, but with multiple slices separated by commas

In [37]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [38]:
# two rows, three columns
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [39]:
# all rows, every other column
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [40]:
# reversed rows and columns
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

##### Accessing array rows and columns
Useful for accessing a single row or column

In [43]:
# first column
print(x2[:, 0])

[12  7  1]


In [44]:
# first row
print(x2[0, :])

[12  5  2  4]


#### Subarrays as no-copy views
numpy makes a view  
python makes a copy  

This allows us to process datasets without making many copies

In [47]:
print(x2)

# create a view
x2_sub = x2[:2, :2]
print(x2_sub)

# modify
x2_sub[0, 0] = 99
print(x2_sub)

# original is modified
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99  5]
 [ 7  6]]
[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#### Creating copies of arrays
We can make a copy of the array with the copy() method

In [50]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

# modify it
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

print(x2)

[[99  5]
 [ 7  6]]
[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


#### Reshaping arrays
Must have the same number of elements

In [53]:
# convert an array from 1 to 9 into a 3x3
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [59]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [60]:
# column vector with reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [61]:
# column vector with newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Array concatenation and splitting

#### Concatin arrays
We can use:
    - np.concatenate
    - np.vstack
    - np.hstack

In [62]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [63]:
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [65]:
grid = np.array([[1,2,3],
                [4,5,6]])

# concatenate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
# concatenate along the second axis (0-indexed)
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [68]:
# working with mixed dimensions, we use vstack or hstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [72]:
# horizontally stack the array
y = np.array([[99],
             [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### Splitting arrays
Used to split arrays:
    - np.split
    - np.hsplit
    - np.vsplit

In [75]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [76]:
grid = np.arange(16).reshape([4,4])
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [79]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### Computation on NumPy Arrays Universal Functions
ufuncs allow for effcient operations

#### The Slowness of loops
Lets look at the speed of a loop

In [2]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range((len(values))):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([ 0.16666667,  1.        ,  0.25      ,  0.25      ,  0.125     ])

In [3]:
big_array = np.random.randint(1, 100, size=1000000)

# benchmark with ipython's magic function %timeit
%timeit compute_reciprocals(big_array)

1 loop, best of 3: 3.83 s per loop


This is very slow. The bottleneck is type checking and the implementation of the function within python

#### UFuncs
Allows for fast vector operations

In [4]:
# way faster
%timeit (1.0 / big_array)

100 loops, best of 3: 6.27 ms per loop


In [5]:
np.arange(5) / np.arange(1, 6)

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [6]:
x = np.arange(9).reshape(3,3)
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### Exploring Numpy's UFuncs
There are 2 types of ufuncs: unary (single input) and binary (2 inputs).

#### Array arithmetic
Uses python's native arithmetic operators

In [8]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division

# additional
print("-x =", -x)
print("x ** 2 =", x ** 2)
print("x % 2 =", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]
-x = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [9]:
# They can be strung together. 
# Standard order of operations is used
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [10]:
# each has a wrapper function as well
np.add(x, 2)

array([2, 3, 4, 5])

#### Absolute value
We can use python's abs function or np's

In [11]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [12]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [13]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [15]:
# Handing complex data where abs returns the magnitude
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([ 5.,  5.,  2.,  1.])

#### Trigonometric Functions

In [16]:
theta = np.linspace(0, np.pi, 3)

In [18]:
# computed to machine precision
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [ 0.          1.57079633  3.14159265]
sin(theta) =  [  0.00000000e+00   1.00000000e+00   1.22464680e-16]
cos(theta) =  [  1.00000000e+00   6.12323400e-17  -1.00000000e+00]
tan(theta) =  [  0.00000000e+00   1.63312394e+16  -1.22464680e-16]


In [19]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [ 3.14159265  1.57079633  0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [21]:
#### Exponents and logarithms

In [22]:
x = [1, 2, 3]
print("x    =", x)
print("e^x  =", np.exp(x))
print("2^x  =", np.exp2(x))
print("3^x  =", np.power(3, x))

x    = [1, 2, 3]
e^x  = [  2.71828183   7.3890561   20.08553692]
2^x  = [ 2.  4.  8.]
3^x  = [ 3  9 27]


In [23]:
x = [1, 2, 4, 10]
print("x    =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x    = [1, 2, 4, 10]
ln(x) = [ 0.          0.69314718  1.38629436  2.30258509]
log2(x) = [ 0.          1.          2.          3.32192809]
log10(x) = [ 0.          0.30103     0.60205999  1.        ]


#### Advanced Ufunc features

##### Specifying output
We can specify the array where the result of a calcuation will be stored. ufuncs all have an out arg to do this.

In [24]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[  0.  10.  20.  30.  40.]


In [25]:
# We can write the results to an array view
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


#### Aggregates
for binary ufunc, there are some interesting aggregate can be computed. 

The reduce elements down to a single value

In [26]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [27]:
np.multiply.reduce(x)

120

In [28]:
# store intermediate results of the computation
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [30]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

#### Outer products
Compute the output of all pairs of 2 different inputs

In [32]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])